language: ruby
rvm:
  - 2.0.0
  - 2.1.2
bundler_args: --jobs=2
script: bundle exec rspec
branches:
  only:
    - master
env:
  global:
    - secure: "QSJasTVQQXuNes134v4iQLGBz3FQmLzGszd2u7Pa1HKHK8NfWyugVKx/nAnbvjziTj2JugAsLURqQNe+gw46oRPhOjiGAcG5aFYFR5/tCXNi5WpFOymG6jNIRFaZT9mFzHel07q1Z2CL+OrTZuONsVF3Dxykwg0Cm89huQa12YI="
